from __future__ import annotations

import logging
from typing import Dict, List

import requests

logger = logging.getLogger(__name__)


class OllamaGenerator:
    """Simple local generator using Ollama HTTP API."""

    def __init__(self, model_name: str = "mistral", base_url: str = "http://localhost:11434") -> None:
        self.model_name = model_name
        self.base_url = base_url.rstrip("/")

    def generate(self, prompt: str, timeout: int = 90) -> str:
        payload = {"model": self.model_name, "prompt": prompt, "stream": False}
        url = f"{self.base_url}/api/generate"

        try:
            response = requests.post(url, json=payload, timeout=timeout)
            response.raise_for_status()
            data = response.json()
            text = data.get("response", "").strip()
            if not text:
                return "No response generated by local model."
            return text
        except requests.exceptions.RequestException as exc:
            logger.warning("Ollama request failed: %s", exc)
            raise RuntimeError("Failed to connect to Ollama. Ensure `ollama serve` is running.") from exc


def extractive_fallback(query: str, retrieved_chunks: List[Dict[str, object]], max_chunks: int = 3) -> str:
    """Fallback extractive answer when local LLM is unavailable."""
    if not retrieved_chunks:
        return "Insufficient context to answer the question. Sources: none."

    selected = retrieved_chunks[:max_chunks]
    evidence = " ".join(str(c["content"]) for c in selected)
    short_evidence = evidence[:900].strip()
    citations = ", ".join(f"{c['doc_id']}::{c['chunk_id']}" for c in selected)

    return (
        f"Query: {query}\n"
        f"Extractive summary: {short_evidence}\n"
        f"Sources: {citations}"
    )
